# Generated by Django 4.2 on 2023-04-30 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название ингредиента",
                        max_length=200,
                        verbose_name="название ингредиента",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="Введите единицу измерения",
                        max_length=10,
                        verbose_name="единица измерения",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags",
                    models.SlugField(
                        help_text="Введите таг для ингредиента",
                        unique=True,
                        verbose_name="таг ингредиента",
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте картинку",
                        verbose_name="картинка",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название рецепта",
                        max_length=200,
                        verbose_name="название рецепта",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст рецепта", verbose_name="текст рецепта"
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Введите название тега",
                        unique=True,
                        verbose_name="название тега",
                    ),
                ),
                ("color", models.CharField(max_length=9)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Введите тег", unique=True, verbose_name="тег"
                    ),
                ),
            ],
        ),
    ]
